// SPDX-License-Identifier: GPL-2.0-only
/* Auto-generated by perf_test_gen/run_workload_pipeline.py */
/* Workload profile: mprotect_paths */
/* Source file: linux-v6.19/mm/mprotect.c */

#define _GNU_SOURCE
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#ifndef CLOCK_MONOTONIC_RAW
#define CLOCK_MONOTONIC_RAW CLOCK_MONOTONIC
#endif

enum ptg_touch_mode {
    PTG_TOUCH_READ = 0,
    PTG_TOUCH_WRITE = 1,
};

struct ptg_mprotect_scenario {
    const char *name;
    const char *pattern;
    size_t mapping_bytes;
    size_t protect_bytes;
    unsigned int rounds;
    unsigned int max_rounds;
    uint64_t min_measure_ns;
    unsigned int batch_ops;
    unsigned int toggle_loops;
    unsigned int touch_passes;
    unsigned int warmup_rounds;
    int prefault_before_protect;
    int collect_vm_snapshot;
    enum ptg_touch_mode post_touch_mode;
    int shared_mapping;
    int expect_success;
};

struct ptg_run_result {
    uint64_t prefault_ns;
    uint64_t protect_ns;
    uint64_t restore_ns;
    uint64_t post_touch_ns;
    uint64_t pages_touched;
    uint64_t protected_pages;
    uint64_t split_vmas;
    uint64_t final_vmas;
    uint64_t expected_matches;
    uint64_t unexpected_results;
    uint64_t errno_enomem;
    uint64_t errno_eacces;
    uint64_t errno_einval;
    uint64_t errno_other;
    uint64_t checksum;
    uint64_t batch_probe_available;
    uint64_t batch_calls;
    uint64_t batch_total_ptes;
    uint64_t batch_nr_1;
    uint64_t batch_nr_2_15;
    uint64_t batch_nr_16_63;
    uint64_t batch_nr_64_511;
    uint64_t batch_nr_512_plus;
    uint64_t huge_pmd_probe_available;
    uint64_t huge_pmd_calls;
    uint64_t huge_pmd_ret_zero;
    uint64_t huge_pmd_ret_one;
    uint64_t huge_pmd_ret_hpage;
    uint64_t huge_pmd_nonpresent;
    uint64_t smaps_before_protect_found;
    uint64_t smaps_before_protect_anon_huge_kb;
    uint64_t smaps_before_protect_kernel_page_kb;
    uint64_t smaps_before_protect_mmu_page_kb;
    uint64_t smaps_before_protect_thpeligible;
    uint64_t smaps_after_restore_found;
    uint64_t smaps_after_restore_anon_huge_kb;
    uint64_t smaps_after_restore_kernel_page_kb;
    uint64_t smaps_after_restore_mmu_page_kb;
    uint64_t smaps_after_restore_thpeligible;
    uint64_t pagemap_before_protect_available;
    uint64_t pagemap_before_protect_present_pages;
    uint64_t pagemap_before_protect_soft_dirty_pages;
    uint64_t pagemap_after_restore_available;
    uint64_t pagemap_after_restore_present_pages;
    uint64_t pagemap_after_restore_soft_dirty_pages;
};

struct ptg_smaps_snapshot {
    int found;
    uint64_t anon_huge_kb;
    uint64_t kernel_page_kb;
    uint64_t mmu_page_kb;
    uint64_t thpeligible;
};

struct ptg_pagemap_snapshot {
    int available;
    uint64_t present_pages;
    uint64_t soft_dirty_pages;
};

static volatile unsigned long benchmark_sink;

static int ptg_reset_mprotect_batch_probe(void)
{
    FILE *probe = fopen("/proc/ptg_mprotect_batch", "w");
    if (!probe)
        return 0;
    fputs("reset\n", probe);
    fclose(probe);
    return 1;
}

static void ptg_read_mprotect_batch_probe(struct ptg_run_result *result)
{
    char line[128];
    FILE *probe = fopen("/proc/ptg_mprotect_batch", "r");
    if (!probe)
        return;
    result->batch_probe_available += 1;
    while (fgets(line, sizeof(line), probe) != NULL) {
        char key[64];
        uint64_t value = 0;
        if (sscanf(line, "%63[^=]=%" SCNu64, key, &value) != 2)
            continue;
        if (strcmp(key, "calls") == 0)
            result->batch_calls += value;
        else if (strcmp(key, "total_ptes") == 0)
            result->batch_total_ptes += value;
        else if (strcmp(key, "nr_1") == 0)
            result->batch_nr_1 += value;
        else if (strcmp(key, "nr_2_15") == 0)
            result->batch_nr_2_15 += value;
        else if (strcmp(key, "nr_16_63") == 0)
            result->batch_nr_16_63 += value;
        else if (strcmp(key, "nr_64_511") == 0)
            result->batch_nr_64_511 += value;
        else if (strcmp(key, "nr_512_plus") == 0)
            result->batch_nr_512_plus += value;
    }
    fclose(probe);
}

static int ptg_reset_mprotect_huge_pmd_probe(void)
{
    FILE *probe = fopen("/proc/ptg_mprotect_huge_pmd", "w");
    if (!probe)
        return 0;
    fputs("reset\n", probe);
    fclose(probe);
    return 1;
}

static void ptg_read_mprotect_huge_pmd_probe(struct ptg_run_result *result)
{
    char line[128];
    FILE *probe = fopen("/proc/ptg_mprotect_huge_pmd", "r");
    if (!probe)
        return;
    result->huge_pmd_probe_available += 1;
    while (fgets(line, sizeof(line), probe) != NULL) {
        char key[64];
        uint64_t value = 0;
        if (sscanf(line, "%63[^=]=%" SCNu64, key, &value) != 2)
            continue;
        if (strcmp(key, "calls") == 0)
            result->huge_pmd_calls += value;
        else if (strcmp(key, "ret_zero") == 0)
            result->huge_pmd_ret_zero += value;
        else if (strcmp(key, "ret_one") == 0)
            result->huge_pmd_ret_one += value;
        else if (strcmp(key, "ret_hpage") == 0)
            result->huge_pmd_ret_hpage += value;
        else if (strcmp(key, "nonpresent") == 0)
            result->huge_pmd_nonpresent += value;
    }
    fclose(probe);
}

static uint64_t ptg_now_ns(void)
{
    struct timespec ts;
    if (clock_gettime(CLOCK_MONOTONIC_RAW, &ts) != 0) {
        if (errno != EINVAL || clock_gettime(CLOCK_MONOTONIC, &ts) != 0) {
            perror("clock_gettime");
            exit(1);
        }
    }
    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}

static size_t ptg_page_size(void)
{
    long value = sysconf(_SC_PAGESIZE);
    if (value <= 0)
        return 4096UL;
    return (size_t)value;
}

static size_t ptg_round_up_page(size_t value, size_t page_size)
{
    return ((value + page_size - 1) / page_size) * page_size;
}

static bool ptg_parse_range_header(const char *line, uintptr_t *start, uintptr_t *end)
{
    unsigned long long lhs = 0;
    unsigned long long rhs = 0;
    if (sscanf(line, "%llx-%llx", &lhs, &rhs) != 2)
        return false;
    *start = (uintptr_t)lhs;
    *end = (uintptr_t)rhs;
    return true;
}

static bool ptg_parse_u64_field(const char *line, const char *prefix, uint64_t *value)
{
    unsigned long long parsed = 0;
    size_t prefix_len = strlen(prefix);
    if (strncmp(line, prefix, prefix_len) != 0)
        return false;
    if (sscanf(line + prefix_len, "%llu", &parsed) != 1)
        return false;
    *value = (uint64_t)parsed;
    return true;
}

static size_t ptg_count_maps_in_range(const unsigned char *start, size_t len)
{
    FILE *maps;
    char line[256];
    uintptr_t begin = (uintptr_t)start;
    uintptr_t end = begin + len;
    size_t count = 0;

    maps = fopen("/proc/self/maps", "r");
    if (!maps)
        return 0;

    while (fgets(line, sizeof(line), maps) != NULL) {
        uintptr_t lhs = 0;
        uintptr_t rhs = 0;
        if (!ptg_parse_range_header(line, &lhs, &rhs))
            continue;
        if (rhs <= begin || lhs >= end)
            continue;
        count += 1;
    }

    fclose(maps);
    return count;
}

static void ptg_collect_smaps_snapshot(void *addr, struct ptg_smaps_snapshot *snapshot)
{
    char line[512];
    uintptr_t target = (uintptr_t)addr;
    bool in_target = false;
    FILE *fp = fopen("/proc/self/smaps", "r");

    memset(snapshot, 0, sizeof(*snapshot));
    if (!fp)
        return;

    while (fgets(line, sizeof(line), fp) != NULL) {
        uintptr_t header_start = 0;
        uintptr_t header_end = 0;

        if (ptg_parse_range_header(line, &header_start, &header_end)) {
            if (in_target)
                break;
            if (target >= header_start && target < header_end) {
                snapshot->found = 1;
                in_target = true;
            }
            continue;
        }

        if (!in_target)
            continue;

        if (ptg_parse_u64_field(line, "AnonHugePages:", &snapshot->anon_huge_kb))
            continue;
        if (ptg_parse_u64_field(line, "KernelPageSize:", &snapshot->kernel_page_kb))
            continue;
        if (ptg_parse_u64_field(line, "MMUPageSize:", &snapshot->mmu_page_kb))
            continue;
        if (ptg_parse_u64_field(line, "THPeligible:", &snapshot->thpeligible))
            continue;
    }

    fclose(fp);
}

static void ptg_collect_pagemap_snapshot(void *addr, size_t len, struct ptg_pagemap_snapshot *snapshot)
{
    size_t page_size = ptg_page_size();
    uint64_t start_page = (uint64_t)((uintptr_t)addr / page_size);
    uint64_t page_count = (uint64_t)(len / page_size);
    int fd = open("/proc/self/pagemap", O_RDONLY | O_CLOEXEC);

    memset(snapshot, 0, sizeof(*snapshot));
    if (fd < 0)
        return;

    for (uint64_t i = 0; i < page_count; ++i) {
        uint64_t entry = 0;
        off_t offset = (off_t)((start_page + i) * sizeof(uint64_t));
        if (pread(fd, &entry, sizeof(entry), offset) != (ssize_t)sizeof(entry)) {
            close(fd);
            return;
        }
        if (entry & (1ULL << 63))
            snapshot->present_pages += 1;
        if (entry & (1ULL << 55))
            snapshot->soft_dirty_pages += 1;
    }

    snapshot->available = 1;
    close(fd);
}

static void ptg_record_errno(struct ptg_run_result *result, int protect_errno)
{
    switch (protect_errno) {
    case 0:
        return;
    case ENOMEM:
        result->errno_enomem += 1;
        return;
    case EACCES:
        result->errno_eacces += 1;
        return;
    case EINVAL:
        result->errno_einval += 1;
        return;
    default:
        result->errno_other += 1;
        return;
    }
}

static void ptg_write_pages(unsigned char *addr, size_t len, unsigned int passes, struct ptg_run_result *result)
{
    size_t page_size = ptg_page_size();
    for (unsigned int pass = 0; pass < passes; ++pass) {
        for (size_t off = 0; off < len; off += page_size) {
            addr[off] = (unsigned char)(addr[off] + 1U);
            result->checksum += addr[off];
            result->pages_touched += 1;
        }
    }
}

static void ptg_read_pages(unsigned char *addr, size_t len, unsigned int passes, struct ptg_run_result *result)
{
    size_t page_size = ptg_page_size();
    for (unsigned int pass = 0; pass < passes; ++pass) {
        for (size_t off = 0; off < len; off += page_size) {
            result->checksum += addr[off];
            result->pages_touched += 1;
        }
    }
}

static void ptg_post_touch(const struct ptg_mprotect_scenario *scenario,
                           unsigned char *region,
                           size_t protect_off,
                           struct ptg_run_result *result)
{
    unsigned char *target = region + protect_off;
    if (scenario->post_touch_mode == PTG_TOUCH_READ)
        ptg_read_pages(target, scenario->protect_bytes, scenario->touch_passes, result);
    else
        ptg_write_pages(target, scenario->protect_bytes, scenario->touch_passes, result);
}

static void ptg_record_expected_match(const struct ptg_mprotect_scenario *scenario,
                                      struct ptg_run_result *result,
                                      int protect_ret,
                                      int protect_errno,
                                      int restore_ret,
                                      int restore_errno,
                                      size_t split_vmas,
                                      size_t final_vmas)
{
    int matched = 0;

    if (protect_ret != 0)
        ptg_record_errno(result, protect_errno);
    if (restore_ret != 0)
        ptg_record_errno(result, restore_errno);

    if (!scenario->expect_success) {
        matched = (protect_ret != 0 || restore_ret != 0);
    } else if (protect_ret == 0 && restore_ret == 0) {
        if (strcmp(scenario->pattern, "anon_split_restore") == 0)
            matched = (split_vmas == 3 && final_vmas == 1);
        else
            matched = (split_vmas == 1 && final_vmas == 1);
    }

    if (matched)
        result->expected_matches += 1;
    else
        result->unexpected_results += 1;
}

static int ptg_run_cycle(const struct ptg_mprotect_scenario *scenario, struct ptg_run_result *result)
{
    size_t page_size = ptg_page_size();
    size_t total_len = ptg_round_up_page(scenario->mapping_bytes, page_size);
    size_t protect_len = ptg_round_up_page(scenario->protect_bytes, page_size);
    size_t protect_off = 0;
    unsigned char *region;
    int map_flags = MAP_ANONYMOUS | (scenario->shared_mapping ? MAP_SHARED : MAP_PRIVATE);
    uint64_t start_ns;
    uint64_t end_ns;
    int protect_ret;
    int restore_ret;
    int protect_errno = 0;
    int restore_errno = 0;
    int last_protect_ret = 0;
    int last_restore_ret = 0;
    int last_protect_errno = 0;
    int last_restore_errno = 0;
    size_t split_vmas = 0;
    size_t final_vmas = 0;

    if (protect_len > total_len)
        protect_len = total_len;

    if (strcmp(scenario->pattern, "anon_split_restore") == 0) {
        if (total_len < page_size * 4)
            total_len = page_size * 4;
        if (protect_len >= total_len)
            protect_len = total_len / 2;
        protect_len = ptg_round_up_page(protect_len, page_size);
        if (protect_len >= total_len)
            protect_len = total_len - page_size;
        protect_off = (total_len - protect_len) / 2;
        protect_off = (protect_off / page_size) * page_size;
    }

    region = mmap(NULL, total_len, PROT_READ | PROT_WRITE, map_flags, -1, 0);
    if (region == MAP_FAILED) {
        perror("mmap");
        return -1;
    }

    if (scenario->prefault_before_protect) {
        struct ptg_run_result prefault = {0};
        start_ns = ptg_now_ns();
        ptg_write_pages(region, total_len, 1, &prefault);
        end_ns = ptg_now_ns();
        result->prefault_ns += end_ns - start_ns;
        result->checksum += prefault.checksum;
    }

    if (scenario->collect_vm_snapshot) {
        struct ptg_smaps_snapshot smaps_before;
        struct ptg_pagemap_snapshot pagemap_before;
        ptg_collect_smaps_snapshot(region + protect_off, &smaps_before);
        ptg_collect_pagemap_snapshot(region + protect_off, protect_len, &pagemap_before);
        result->smaps_before_protect_found += (uint64_t)smaps_before.found;
        result->smaps_before_protect_anon_huge_kb += smaps_before.anon_huge_kb;
        result->smaps_before_protect_kernel_page_kb += smaps_before.kernel_page_kb;
        result->smaps_before_protect_mmu_page_kb += smaps_before.mmu_page_kb;
        result->smaps_before_protect_thpeligible += smaps_before.thpeligible;
        result->pagemap_before_protect_available += (uint64_t)pagemap_before.available;
        result->pagemap_before_protect_present_pages += pagemap_before.present_pages;
        result->pagemap_before_protect_soft_dirty_pages += pagemap_before.soft_dirty_pages;
    }

    for (unsigned int toggle = 0; toggle < scenario->toggle_loops; ++toggle) {
        start_ns = ptg_now_ns();
        protect_ret = mprotect(region + protect_off, protect_len, PROT_READ);
        if (protect_ret != 0)
            protect_errno = errno;
        end_ns = ptg_now_ns();
        result->protect_ns += end_ns - start_ns;

        if (toggle == 0 && protect_ret == 0)
            split_vmas = ptg_count_maps_in_range(region, total_len);

        start_ns = ptg_now_ns();
        restore_ret = mprotect(region + protect_off, protect_len, PROT_READ | PROT_WRITE);
        if (restore_ret != 0)
            restore_errno = errno;
        end_ns = ptg_now_ns();
        result->restore_ns += end_ns - start_ns;

        if (toggle + 1 == scenario->toggle_loops && restore_ret == 0)
            final_vmas = ptg_count_maps_in_range(region, total_len);

        last_protect_ret = protect_ret;
        last_restore_ret = restore_ret;
        last_protect_errno = protect_errno;
        last_restore_errno = restore_errno;

        if (protect_ret != 0 || restore_ret != 0)
            break;
    }
    result->split_vmas += split_vmas;
    result->final_vmas += final_vmas;
    result->protected_pages += (protect_len / page_size) * scenario->toggle_loops;

    if (scenario->collect_vm_snapshot && protect_ret == 0 && restore_ret == 0) {
        struct ptg_smaps_snapshot smaps_after_restore;
        struct ptg_pagemap_snapshot pagemap_after_restore;
        ptg_collect_smaps_snapshot(region + protect_off, &smaps_after_restore);
        ptg_collect_pagemap_snapshot(region + protect_off, protect_len, &pagemap_after_restore);
        result->smaps_after_restore_found += (uint64_t)smaps_after_restore.found;
        result->smaps_after_restore_anon_huge_kb += smaps_after_restore.anon_huge_kb;
        result->smaps_after_restore_kernel_page_kb += smaps_after_restore.kernel_page_kb;
        result->smaps_after_restore_mmu_page_kb += smaps_after_restore.mmu_page_kb;
        result->smaps_after_restore_thpeligible += smaps_after_restore.thpeligible;
        result->pagemap_after_restore_available += (uint64_t)pagemap_after_restore.available;
        result->pagemap_after_restore_present_pages += pagemap_after_restore.present_pages;
        result->pagemap_after_restore_soft_dirty_pages += pagemap_after_restore.soft_dirty_pages;
    }

    ptg_record_expected_match(
        scenario, result, last_protect_ret, last_protect_errno, last_restore_ret, last_restore_errno, split_vmas, final_vmas);

    if (last_protect_ret == 0 && last_restore_ret == 0) {
        struct ptg_run_result post = {0};
        start_ns = ptg_now_ns();
        ptg_post_touch(scenario, region, protect_off, &post);
        end_ns = ptg_now_ns();
        result->post_touch_ns += end_ns - start_ns;
        result->pages_touched += post.pages_touched;
        result->checksum += post.checksum;
    }

    munmap(region, total_len);
    return 0;
}

static int ptg_run_round(const struct ptg_mprotect_scenario *scenario, struct ptg_run_result *result, uint64_t *effective_ops)
{
    *effective_ops = 0;
    for (unsigned int batch = 0; batch < scenario->batch_ops; ++batch) {
        if (ptg_run_cycle(scenario, result) != 0)
            return -1;
        *effective_ops += 1;
    }
    return 0;
}

static const struct ptg_mprotect_scenario ptg_scenarios[] = {
    {
        .name = "anon_full_toggle",
        .pattern = "anon_full_toggle",
        .mapping_bytes = 16384UL * 1024UL,
        .protect_bytes = 16384UL * 1024UL,
        .rounds = 4U,
        .max_rounds = 256U,
        .min_measure_ns = 1200000000ULL,
        .batch_ops = 1U,
        .toggle_loops = 1U,
        .touch_passes = 1U,
        .warmup_rounds = 2U,
        .prefault_before_protect = 1,
        .collect_vm_snapshot = 0,
        .post_touch_mode = PTG_TOUCH_WRITE,
        .shared_mapping = 0,
        .expect_success = 1,
    },
    {
        .name = "anon_split_restore",
        .pattern = "anon_split_restore",
        .mapping_bytes = 32768UL * 1024UL,
        .protect_bytes = 16384UL * 1024UL,
        .rounds = 4U,
        .max_rounds = 256U,
        .min_measure_ns = 1200000000ULL,
        .batch_ops = 1U,
        .toggle_loops = 1U,
        .touch_passes = 1U,
        .warmup_rounds = 2U,
        .prefault_before_protect = 1,
        .collect_vm_snapshot = 0,
        .post_touch_mode = PTG_TOUCH_WRITE,
        .shared_mapping = 0,
        .expect_success = 1,
    },
    {
        .name = "shared_dirty_full_toggle",
        .pattern = "shared_dirty_full_toggle",
        .mapping_bytes = 16384UL * 1024UL,
        .protect_bytes = 16384UL * 1024UL,
        .rounds = 4U,
        .max_rounds = 256U,
        .min_measure_ns = 1200000000ULL,
        .batch_ops = 1U,
        .toggle_loops = 1U,
        .touch_passes = 1U,
        .warmup_rounds = 2U,
        .prefault_before_protect = 1,
        .collect_vm_snapshot = 0,
        .post_touch_mode = PTG_TOUCH_WRITE,
        .shared_mapping = 1,
        .expect_success = 1,
    },
    {
        .name = "shared_dirty_full_toggle_64m",
        .pattern = "shared_dirty_full_toggle",
        .mapping_bytes = 65536UL * 1024UL,
        .protect_bytes = 65536UL * 1024UL,
        .rounds = 4U,
        .max_rounds = 256U,
        .min_measure_ns = 1200000000ULL,
        .batch_ops = 1U,
        .toggle_loops = 1U,
        .touch_passes = 1U,
        .warmup_rounds = 2U,
        .prefault_before_protect = 1,
        .collect_vm_snapshot = 0,
        .post_touch_mode = PTG_TOUCH_WRITE,
        .shared_mapping = 1,
        .expect_success = 1,
    },
};

int main(int argc, char **argv)
{
    const char *filter = argc > 1 ? argv[1] : NULL;
    unsigned int external_rounds = argc > 2 ? (unsigned int)strtoul(argv[2], NULL, 10) : 1U;
    int ran = 0;

    if (external_rounds == 0)
        external_rounds = 1;

    printf("workload=%s source=%s scenarios=%zu rounds=%u\n",
           "mprotect_paths", "linux-v6.19/mm/mprotect.c",
           sizeof(ptg_scenarios) / sizeof(ptg_scenarios[0]), external_rounds);

    for (size_t i = 0; i < sizeof(ptg_scenarios) / sizeof(ptg_scenarios[0]); ++i) {
        struct ptg_run_result aggregate;
        uint64_t total_rounds = 0;
        memset(&aggregate, 0, sizeof(aggregate));

        if (filter && strcmp(filter, ptg_scenarios[i].name) != 0)
            continue;

        for (unsigned int outer = 0; outer < external_rounds; ++outer) {
            struct ptg_run_result sample;
            uint64_t sample_total_ns = 0;
            unsigned int sample_rounds = 0;
            uint64_t sample_effective_rounds = 0;
            memset(&sample, 0, sizeof(sample));
            for (unsigned int warmup = 0; warmup < ptg_scenarios[i].warmup_rounds; ++warmup) {
                struct ptg_run_result warmup_result;
                uint64_t warmup_effective_ops = 0;
                memset(&warmup_result, 0, sizeof(warmup_result));
                if (ptg_run_round(&ptg_scenarios[i], &warmup_result, &warmup_effective_ops) != 0)
                    return 1;
            }
            ptg_reset_mprotect_batch_probe();
            ptg_reset_mprotect_huge_pmd_probe();
            do {
                uint64_t effective_ops = 0;
                if (ptg_run_round(&ptg_scenarios[i], &sample, &effective_ops) != 0)
                    return 1;
                sample_rounds += 1;
                sample_effective_rounds += effective_ops;
                sample_total_ns = sample.prefault_ns + sample.protect_ns + sample.restore_ns + sample.post_touch_ns;
            } while (sample_rounds < ptg_scenarios[i].rounds ||
                     (ptg_scenarios[i].min_measure_ns > 0 &&
                      sample_total_ns < ptg_scenarios[i].min_measure_ns &&
                      sample_rounds < ptg_scenarios[i].max_rounds));
            ptg_read_mprotect_batch_probe(&sample);
            ptg_read_mprotect_huge_pmd_probe(&sample);
            aggregate.prefault_ns += sample.prefault_ns;
            aggregate.protect_ns += sample.protect_ns;
            aggregate.restore_ns += sample.restore_ns;
            aggregate.post_touch_ns += sample.post_touch_ns;
            aggregate.pages_touched += sample.pages_touched;
            aggregate.protected_pages += sample.protected_pages;
            aggregate.split_vmas += sample.split_vmas;
            aggregate.final_vmas += sample.final_vmas;
            aggregate.expected_matches += sample.expected_matches;
            aggregate.unexpected_results += sample.unexpected_results;
            aggregate.errno_enomem += sample.errno_enomem;
            aggregate.errno_eacces += sample.errno_eacces;
            aggregate.errno_einval += sample.errno_einval;
            aggregate.errno_other += sample.errno_other;
            aggregate.checksum += sample.checksum;
            aggregate.batch_probe_available += sample.batch_probe_available;
            aggregate.batch_calls += sample.batch_calls;
            aggregate.batch_total_ptes += sample.batch_total_ptes;
            aggregate.batch_nr_1 += sample.batch_nr_1;
            aggregate.batch_nr_2_15 += sample.batch_nr_2_15;
            aggregate.batch_nr_16_63 += sample.batch_nr_16_63;
            aggregate.batch_nr_64_511 += sample.batch_nr_64_511;
            aggregate.batch_nr_512_plus += sample.batch_nr_512_plus;
            aggregate.huge_pmd_probe_available += sample.huge_pmd_probe_available;
            aggregate.huge_pmd_calls += sample.huge_pmd_calls;
            aggregate.huge_pmd_ret_zero += sample.huge_pmd_ret_zero;
            aggregate.huge_pmd_ret_one += sample.huge_pmd_ret_one;
            aggregate.huge_pmd_ret_hpage += sample.huge_pmd_ret_hpage;
            aggregate.huge_pmd_nonpresent += sample.huge_pmd_nonpresent;
            aggregate.smaps_before_protect_found += sample.smaps_before_protect_found;
            aggregate.smaps_before_protect_anon_huge_kb += sample.smaps_before_protect_anon_huge_kb;
            aggregate.smaps_before_protect_kernel_page_kb += sample.smaps_before_protect_kernel_page_kb;
            aggregate.smaps_before_protect_mmu_page_kb += sample.smaps_before_protect_mmu_page_kb;
            aggregate.smaps_before_protect_thpeligible += sample.smaps_before_protect_thpeligible;
            aggregate.smaps_after_restore_found += sample.smaps_after_restore_found;
            aggregate.smaps_after_restore_anon_huge_kb += sample.smaps_after_restore_anon_huge_kb;
            aggregate.smaps_after_restore_kernel_page_kb += sample.smaps_after_restore_kernel_page_kb;
            aggregate.smaps_after_restore_mmu_page_kb += sample.smaps_after_restore_mmu_page_kb;
            aggregate.smaps_after_restore_thpeligible += sample.smaps_after_restore_thpeligible;
            aggregate.pagemap_before_protect_available += sample.pagemap_before_protect_available;
            aggregate.pagemap_before_protect_present_pages += sample.pagemap_before_protect_present_pages;
            aggregate.pagemap_before_protect_soft_dirty_pages += sample.pagemap_before_protect_soft_dirty_pages;
            aggregate.pagemap_after_restore_available += sample.pagemap_after_restore_available;
            aggregate.pagemap_after_restore_present_pages += sample.pagemap_after_restore_present_pages;
            aggregate.pagemap_after_restore_soft_dirty_pages += sample.pagemap_after_restore_soft_dirty_pages;
            total_rounds += sample_effective_rounds ? sample_effective_rounds : sample_rounds;
        }

        if (total_rounds == 0)
            total_rounds = (uint64_t)external_rounds * ptg_scenarios[i].rounds;

        benchmark_sink += (unsigned long)aggregate.checksum;
        benchmark_sink += (unsigned long)aggregate.split_vmas;
        benchmark_sink += (unsigned long)aggregate.final_vmas;
        printf("scenario=%s pattern=%s rounds=%u internal_rounds=%" PRIu64 " mapping_kb=%zu protect_kb=%zu shared=%d warmup_rounds=%u toggle_loops=%u "
               "prefault_ns_avg=%" PRIu64 " protect_ns_avg=%" PRIu64 " restore_ns_avg=%" PRIu64 " "
               "post_touch_ns_avg=%" PRIu64 " cycle_ns_avg=%" PRIu64 " "
               "protect_ns_per_page=%" PRIu64 " restore_ns_per_page=%" PRIu64 " cycle_ns_per_page=%" PRIu64 " "
               "split_vmas_avg=%" PRIu64 " final_vmas_avg=%" PRIu64 " "
               "batch_probe_available=%" PRIu64 " mprotect_batch_calls=%" PRIu64 " mprotect_batch_total_ptes=%" PRIu64 " "
               "mprotect_batch_mean_nr_ptes=%" PRIu64 " mprotect_batch_nr_1=%" PRIu64 " mprotect_batch_nr_2_15=%" PRIu64 " "
               "mprotect_batch_nr_16_63=%" PRIu64 " mprotect_batch_nr_64_511=%" PRIu64 " mprotect_batch_nr_512_plus=%" PRIu64 " "
               "huge_pmd_probe_available=%" PRIu64 " mprotect_huge_pmd_calls=%" PRIu64 " mprotect_huge_pmd_ret_0=%" PRIu64 " "
               "mprotect_huge_pmd_ret_1=%" PRIu64 " mprotect_huge_pmd_ret_hpage=%" PRIu64 " mprotect_huge_pmd_nonpresent=%" PRIu64 " "
               "smaps_before_protect_found=%" PRIu64 " smaps_before_protect_anon_huge_kb_avg=%" PRIu64 " "
               "smaps_before_protect_kernel_page_kb_avg=%" PRIu64 " smaps_before_protect_mmu_page_kb_avg=%" PRIu64 " "
               "smaps_before_protect_thpeligible_pct=%" PRIu64 " "
               "smaps_after_restore_found=%" PRIu64 " smaps_after_restore_anon_huge_kb_avg=%" PRIu64 " "
               "smaps_after_restore_kernel_page_kb_avg=%" PRIu64 " smaps_after_restore_mmu_page_kb_avg=%" PRIu64 " "
               "smaps_after_restore_thpeligible_pct=%" PRIu64 " "
               "pagemap_before_protect_available=%" PRIu64 " pagemap_before_protect_present_pages_avg=%" PRIu64 " "
               "pagemap_before_protect_soft_dirty_pages_avg=%" PRIu64 " "
               "pagemap_after_restore_available=%" PRIu64 " pagemap_after_restore_present_pages_avg=%" PRIu64 " "
               "pagemap_after_restore_soft_dirty_pages_avg=%" PRIu64 " "
               "expected_match_ratio=%" PRIu64 " unexpected_results=%" PRIu64 " "
               "errno_enomem=%" PRIu64 " errno_eacces=%" PRIu64 " errno_einval=%" PRIu64 " errno_other=%" PRIu64 " checksum=%" PRIu64 "\n",
               ptg_scenarios[i].name,
               ptg_scenarios[i].pattern,
               external_rounds,
               total_rounds,
               ptg_scenarios[i].mapping_bytes / 1024UL,
               ptg_scenarios[i].protect_bytes / 1024UL,
               ptg_scenarios[i].shared_mapping,
               ptg_scenarios[i].warmup_rounds,
               ptg_scenarios[i].toggle_loops,
               total_rounds ? (aggregate.prefault_ns / total_rounds) : 0,
               total_rounds ? (aggregate.protect_ns / total_rounds) : 0,
               total_rounds ? (aggregate.restore_ns / total_rounds) : 0,
               total_rounds ? (aggregate.post_touch_ns / total_rounds) : 0,
               total_rounds ? ((aggregate.protect_ns + aggregate.restore_ns + aggregate.post_touch_ns) / total_rounds) : 0,
               aggregate.protected_pages ? (aggregate.protect_ns / aggregate.protected_pages) : 0,
               aggregate.protected_pages ? (aggregate.restore_ns / aggregate.protected_pages) : 0,
               aggregate.protected_pages ? ((aggregate.protect_ns + aggregate.restore_ns + aggregate.post_touch_ns) / aggregate.protected_pages) : 0,
               total_rounds ? (aggregate.split_vmas / total_rounds) : 0,
               total_rounds ? (aggregate.final_vmas / total_rounds) : 0,
               aggregate.batch_probe_available,
               aggregate.batch_calls,
               aggregate.batch_total_ptes,
               aggregate.batch_calls ? (aggregate.batch_total_ptes / aggregate.batch_calls) : 0,
               aggregate.batch_nr_1,
               aggregate.batch_nr_2_15,
               aggregate.batch_nr_16_63,
               aggregate.batch_nr_64_511,
               aggregate.batch_nr_512_plus,
               aggregate.huge_pmd_probe_available,
               aggregate.huge_pmd_calls,
               aggregate.huge_pmd_ret_zero,
               aggregate.huge_pmd_ret_one,
               aggregate.huge_pmd_ret_hpage,
               aggregate.huge_pmd_nonpresent,
               aggregate.smaps_before_protect_found,
               aggregate.smaps_before_protect_found ? (aggregate.smaps_before_protect_anon_huge_kb / aggregate.smaps_before_protect_found) : 0,
               aggregate.smaps_before_protect_found ? (aggregate.smaps_before_protect_kernel_page_kb / aggregate.smaps_before_protect_found) : 0,
               aggregate.smaps_before_protect_found ? (aggregate.smaps_before_protect_mmu_page_kb / aggregate.smaps_before_protect_found) : 0,
               aggregate.smaps_before_protect_found ? (uint64_t)((aggregate.smaps_before_protect_thpeligible * 100ULL) / aggregate.smaps_before_protect_found) : 0,
               aggregate.smaps_after_restore_found,
               aggregate.smaps_after_restore_found ? (aggregate.smaps_after_restore_anon_huge_kb / aggregate.smaps_after_restore_found) : 0,
               aggregate.smaps_after_restore_found ? (aggregate.smaps_after_restore_kernel_page_kb / aggregate.smaps_after_restore_found) : 0,
               aggregate.smaps_after_restore_found ? (aggregate.smaps_after_restore_mmu_page_kb / aggregate.smaps_after_restore_found) : 0,
               aggregate.smaps_after_restore_found ? (uint64_t)((aggregate.smaps_after_restore_thpeligible * 100ULL) / aggregate.smaps_after_restore_found) : 0,
               aggregate.pagemap_before_protect_available,
               aggregate.pagemap_before_protect_available ? (aggregate.pagemap_before_protect_present_pages / aggregate.pagemap_before_protect_available) : 0,
               aggregate.pagemap_before_protect_available ? (aggregate.pagemap_before_protect_soft_dirty_pages / aggregate.pagemap_before_protect_available) : 0,
               aggregate.pagemap_after_restore_available,
               aggregate.pagemap_after_restore_available ? (aggregate.pagemap_after_restore_present_pages / aggregate.pagemap_after_restore_available) : 0,
               aggregate.pagemap_after_restore_available ? (aggregate.pagemap_after_restore_soft_dirty_pages / aggregate.pagemap_after_restore_available) : 0,
               (uint64_t)(total_rounds ? ((aggregate.expected_matches * 100ULL) / total_rounds) : 0),
               aggregate.unexpected_results,
               aggregate.errno_enomem,
               aggregate.errno_eacces,
               aggregate.errno_einval,
               aggregate.errno_other,
               aggregate.checksum);
        ran = 1;
    }

    if (!ran) {
        fprintf(stderr, "no scenarios matched filter %s\n", filter ? filter : "<none>");
        return 1;
    }

    return 0;
}
